baseURL: https://bluevolvo87.github.io/themedianduck/
languageCode: en-us
title: The Median Duck
theme: archie
copyright: © The Median Duck
pygmentsstyle: monokai
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
params:
  mode: toggle
  social:
    - icon: github
      name: GitHub
      url: https://github.com/bluevolvo87/themedianduck
    
    - icon: youtube
      name: YouTube
      url: https://youtube.com/naanbread87/
  subtitle: vires in notitia
  useCDN: no
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts 
      url: /posts
      weight: 2
    - name: The Vision
      url: /vision
      weight: 3
    - name: About Me
      url: /about
      weight: 4
    - name: Categories
      url: /tags
      weight: 5
