---
aliases:
- "about-me"
author: Christopher Nam
date: "2024-07-08"
description: About Me
title: About Me
---

# My Professional Background

I obtained a PhD in Statistics from the University of Warwick in 2013, my thesis title was *"Uncertainty in Changepoints in Time Series"* [^1]. I'm delighted that Dr Little Alex Horne recently became associated with my alma mater through the [Taskmaster Education](https://taskmastereducation.com/news/dr-little-alex-horne) scheme.

[^1]: I'm sure you eager readers can find my thesis online and be gently amused by my chapter quotes.

I have 10 years of industry experience as a Research Scientist/Data Scientist at Amazon and Samsung, predominantly demand forecasting at scale for products. From this experience, I have some experience on running projects at scale, with rigor (automation, repeatability) and compromises that need to be made (whether it be technical, monetary, mental).

# My Personal Motivation

There are a variety of personal reasons why I am starting *The Median Duck*.

Perhaps optimistically, I want to (stealthy) educate others of analytics to the general public in a fun and amusing manner. Statistics is not taught particularly well in the UK, often seen as a boring number crunching and often a medium to lie. Add to this, I want to instill best practices and the graft work that I have experienced over my years, and that are often overlooked in courses and textbooks (importance of good quality data, automated workflows, etc.).

I made the somewhat brave decision to become self employed at the start of 2024, and have various ventures in the work to provide some income and keep me entertained on a daily basis (piano teaching, piano performance, admin for my housing association). The Median Duck is one of these ventures.

I don't expect this venture to be a money maker (major or minor), but I do want to retain my engagement in the data science and statistics field. Add to this, my "imposter syndrome" often wants me to relearn the basics.

I do have some aspirations to potentially go into data journalism through data science and analytics and this venture may provide some experience and build up a portfolio of work.

Finally, I do not claim to be a full expert and entirely knowledgeable about the analysis I will be covering[^2]. However I'm always eager to learn new topics and also educate others; I believe I am an educator and teacher at my core. My passion for Taskmaster and prior experience with the analytics field thus makes *The Median Duck* this the ideal vehicle.

[^2]: This is the [Imposter Syndrome](https://www.webmd.com/balance/what-is-imposter-syndrome) talking for the most part...

# My Taskmaster Journey

My Taskmaster journey properly started during 2020 (and the global pandemic), when the Series 2 task "order something without using certain words" was recommended to me on YouTube. Once I watched this task, I was hooked and consequently went down the Taskmaster rabbit hole and binged whatever series were available.

However, prior to this, I was initially quite dismissive of Taskmaster. I had previously associated "Taskmaster" with "Ticketmaster" and thus erroneously thought it was going to be a dull show in which extortionate ticket scalping would occur. How wrong I was...

Since 2020, I have watched each series of Taskmaster (mainly UK) near the time of broadcast, and consumed Taskmaster adjacent material (the podcast, comedians appearances on other comedy shows etc.).

I have also unofficially (and jokingly) assigned myself the title of *"Taskmaster Representative of the Pacific Northwest"* as I have referred numerous friends and colleagues about Taskmaster and also informed them of when the next series is broadcasting.

# These are a Few of My Favourite Taskmaster Things...

-   **Favourite Task:** Ringtone Choreography (S4E4)
-   **Favourite Series:** Series 4 or 5.
-   **Favourite Contestant:** Victoria Coren Mitchell[^3]
-   **Favourite Quote(s):** "Friendship is Truth"
-   **Degrees of Separation to Alex Horne (to my knowledge):** 3

[^3]: Fun fact: I actively squealed when VCM was announced. She's a fascinating person with extremely varied career (to name a few: author, broadcaster/presenter, professional player, pornographer, former stand up comedian, customised inhaler trendsetter...)
